### ISSUE TITLE
Documentation for easy usage

### ISSUE THREAD

**Issue by velia-vito** [mayankofficial999/easy_firebase#1]
Consider writing up documentation so that it's easier to use the package. Others don't quite have the understanding/thought process you had while writing the code.

Maybe consider using the `public_member_api_docs` linter rule. (https://github.com/shady-ti/meku-ui/blob/3a74592ca740472f47962e4a0e421938c915d0a3/analysis_options.yaml#L7-L9, you can run dartdoc on that package if you want an exampel)

Willing to refactor/write docs if you're willing to pop in and tell me what is what if I don't understand the code.

**Comment by mayankofficial999** [comment]
Hey @velia-vito   

I have updated the codebase with documentation comments
<code>dartdoc</code> should generate the necessary API documentation needed.  

I hope this helps
